#pragma once

// The Unicode facts the tokenizer needs: general-category classes for the
// pre-tokenizer pattern, White_Space, NFC. Tables are generated by
// tools/gen_unicode.py into unicode_tables.inc.

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace navi::text {

enum class Cat : std::uint8_t { Other = 0, Lu = 1, Ll = 2, Lt = 3, Lm = 4, Lo = 5, M = 6, N = 7 };

Cat  category(char32_t cp);
bool is_white_space(char32_t cp);      // Unicode White_Space (\s in the pre-tokenizer)
inline bool is_letter(Cat c) { return c >= Cat::Lu && c <= Cat::Lo; }

// Canonical decomposition + ordering + composition. Hangul handled algorithmically.
std::u32string nfc(std::u32string_view s);

// UTF-8 <-> code points. Invalid sequences decode to U+FFFD, one per bad byte.
std::u32string utf8_decode(std::string_view s);
void           utf8_append(std::string & out, char32_t cp);
std::string    utf8_encode(std::u32string_view s);

} // namespace navi::text
