#!/usr/bin/env python3
"""Generate runtime/text/unicode_tables.inc from Python's Unicode database.

    uv run gen_unicode.py > ../runtime/text/unicode_tables.inc

What the tokenizer's pre-tokenizer and NFC normalizer need, nothing more:
general-category ranges (only the classes the pattern distinguishes),
canonical decompositions, canonical combining classes and the primary
composites. White_Space is the fixed PropList set, written by hand below.
"""
import sys
import unicodedata

CLASSES = {"Lu": 1, "Ll": 2, "Lt": 3, "Lm": 4, "Lo": 5, "Mn": 6, "Mc": 6, "Me": 6, "Nd": 7, "Nl": 7, "No": 7}
NAMES = {1: "Lu", 2: "Ll", 3: "Lt", 4: "Lm", 5: "Lo", 6: "M", 7: "N"}

# Unicode PropList White_Space (stable since 3.x)
WHITE_SPACE = [(0x9, 0xD), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0), (0x1680, 0x1680), (0x2000, 0x200A),
               (0x2028, 0x2029), (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]

HANGUL_S, HANGUL_N = 0xAC00, 11172


def category_ranges():
    out, start, cur = [], None, 0
    for cp in range(0x110000):
        c = CLASSES.get(unicodedata.category(chr(cp)), 0)
        if c != cur:
            if cur:
                out.append((start, cp - 1, cur))
            start, cur = cp, c
    if cur:
        out.append((start, 0x10FFFF, cur))
    return out


def canonical_decomp(cp):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        return None
    return [int(x, 16) for x in d.split()]


def main():
    w = sys.stdout.write
    w(f"// Generated by tools/gen_unicode.py from Python {sys.version.split()[0]} unicodedata "
      f"(Unicode {unicodedata.unidata_version}). Do not edit.\n\n")

    ranges = category_ranges()
    w(f"// {{first, last, class}}; class: 1 Lu, 2 Ll, 3 Lt, 4 Lm, 5 Lo, 6 M, 7 N. Sorted, non-overlapping.\n")
    w(f"static const CatRange CAT_RANGES[{len(ranges)}] = {{\n")
    for a, b, c in ranges:
        w(f"    {{0x{a:X}, 0x{b:X}, {c}}},\n")
    w("};\n\n")

    w(f"static const CpRange WHITE_SPACE[{len(WHITE_SPACE)}] = {{\n")
    for a, b in WHITE_SPACE:
        w(f"    {{0x{a:X}, 0x{b:X}}},\n")
    w("};\n\n")

    decomps = []
    for cp in range(0x110000):
        if HANGUL_S <= cp < HANGUL_S + HANGUL_N:
            continue
        d = canonical_decomp(cp)
        if d:
            assert 1 <= len(d) <= 2, (cp, d)
            decomps.append((cp, d[0], d[1] if len(d) == 2 else 0))
    w("// canonical decompositions, first level: {cp, a, b} (b == 0: singleton). Hangul is algorithmic.\n")
    w(f"static const Decomp DECOMPS[{len(decomps)}] = {{\n")
    for cp, a, b in decomps:
        w(f"    {{0x{cp:X}, 0x{a:X}, 0x{b:X}}},\n")
    w("};\n\n")

    cccs = [(cp, unicodedata.combining(chr(cp))) for cp in range(0x110000) if unicodedata.combining(chr(cp))]
    w(f"static const Ccc CCCS[{len(cccs)}] = {{\n")
    for cp, c in cccs:
        w(f"    {{0x{cp:X}, {c}}},\n")
    w("};\n\n")

    # primary composites: pair decompositions whose character recomposes under NFC
    comps = []
    for cp, a, b in decomps:
        if b == 0:
            continue
        if unicodedata.normalize("NFC", unicodedata.normalize("NFD", chr(cp))) != chr(cp):
            continue  # composition exclusion
        if unicodedata.combining(chr(a)) != 0:
            continue  # non-starter decomposition: never composes
        comps.append((a, b, cp))
    comps.sort()
    w("// primary composites {a, b, composed}, sorted by (a, b)\n")
    w(f"static const Comp COMPS[{len(comps)}] = {{\n")
    for a, b, cp in comps:
        w(f"    {{0x{a:X}, 0x{b:X}, 0x{cp:X}}},\n")
    w("};\n")


if __name__ == "__main__":
    main()
